### ISSUE TITLE
Server does not prompt client certificate

### ISSUE THREAD

**Issue by vwhoho** [typesafehub/activator-play-tls-example#46]
I want to use the CustomSSLEngineProvider in Play to do 2-way SSL. Even though needClientAuth=true, the server does not request the client to send its certificate. 

Details follow:
1) I use self sign server and client certificate
2) I perform https on Chrome to hit the site. It said connection is not private but I chose Advanced to proceed 
3) Then I got the content from the server 

Step 3) shouldn't just happen because the server is expected to request a certificate from the client and Chrome will prompt me to send a certificate. But that didn't happen

Can you give me any clue why

**Comment by wsargent** [comment]
@vwhoho please provide a repeatable test case -- you need to use `./play` and ensure that you have the script properly set up.

**Comment by ghost** [comment]
@vwhoho, have you ever managed to make your play app to ask for client certificate? I have the same issue, the certificate is not being asked neither in dev nor in prod mode despite needClientAuth set to true. I am using self-signed server certificate generated by means of play and akka http as a transport.

**Comment by wsargent** [comment]
Are you following the directions in https://github.com/playframework/play-scala-tls-example#turning-on-client-authentication ?

**Comment by ghost** [comment]
@wsargent, yeap
Here is the command I run to start my app from IDEA by means of SBT task:
`run -Dhttp.port=disabled -Djavax.net.debug=ssl:handshake -Dhttps.port=9999 -Dplay.ssl.needClientAuth=true  -Dplay.ssl.wantClientAuth=true -Dconfig.file=envs/application.local.conf -Dssl-config.sslParameters.clientAuth=need -Dplay.ws.clientAuth.sslParameters.clientAuth=need`

I have tried all possible parameters to configure client auth above =)

**Comment by wsargent** [comment]
Well in that case, the next step is to use the debugger and set a breakpoint, and connect to the remote process through IDEA's debug menu:

https://www.playframework.com/documentation/2.6.x/PlayConsole#Debugging

and

https://www.jetbrains.com/help/idea/run-debug-configuration-remote-debug.html

**Comment by wsargent** [comment]
Also, try the `play` command rather than running it in Intellij IDEA.

**Comment by octonato** [comment]
This issue seems to be forgotten. I'm closing it. Please, re-open if still not working.

**Comment by ronyyin** [comment]
> run -Dhttp.port=disabled -Djavax.net.debug=ssl:handshake -Dhttps.port=9999 -Dplay.ssl.needClientAuth=true -Dplay.ssl.wantClientAuth=true -Dconfig.file=envs/application.local.conf -Dssl-config.sslParameters.clientAuth=need -Dplay.ws.clientAuth.sslParameters.clientAuth=need

Did you fix it?

**Comment by ronyyin** [comment]
> I want to use the CustomSSLEngineProvider in Play to do 2-way SSL. Even though needClientAuth=true, the server does not request the client to send its certificate.
> 
> Details follow:
> 
> 1. I use self sign server and client certificate
> 2. I perform https on Chrome to hit the site. It said connection is not private but I chose Advanced to proceed
> 3. Then I got the content from the server
> 
> Step 3) shouldn't just happen because the server is expected to request a certificate from the client and Chrome will prompt me to send a certificate. But that didn't happen
> 
> Can you give me any clue why

Have you fixed it? how?

**Comment by wsargent** [comment]
"shouldn't just happen because the server is expected to request a certificate from the client and Chrome will prompt me to send a certificate. But that didn't happen"

This isn't accurate.  The client certificate request is on the TLS handshake, it's not something you do with a browser.
