### ISSUE TITLE
Problem deploying

### ISSUE THREAD

**Issue by devamondos** [typesafehub/activator-play-tls-example#94]
I can run this locally but I am getting this error when deploying (with Docker on OpenShift): 

Uncaught error from thread [application-akka.actor.default-dispatcher-6]: state, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
--
  | java.lang.NoSuchFieldError: state
  | at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:218)
  | at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
  | at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
  | at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
  | at akka.stream.impl.io.TLSActor.runDelegatedTasks(TLSActor.scala:404)
  | at akka.stream.impl.io.TLSActor.doUnwrap(TLSActor.scala:373)
  | at akka.stream.impl.io.TLSActor.doInbound(TLSActor.scala:292)
  | at akka.stream.impl.io.TLSActor.$anonfun$bidirectional$1(TLSActor.scala:227)
  | at akka.stream.impl.Pump.pump(Transfer.scala:201)
  | at akka.stream.impl.Pump.pump$(Transfer.scala:199)
  | at akka.stream.impl.io.TLSActor.pump(TLSActor.scala:50)
  | at akka.stream.impl.SimpleOutputs$$anonfun$downstreamRunning$1.applyOrElse(ActorProcessor.scala:239)
  | at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
  | at akka.stream.impl.SubReceive.apply(Transfer.scala:18)
  | at akka.stream.impl.FanOut$OutputBunch$$anonfun$subreceive$1.applyOrElse(FanOut.scala:231)
  | at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
  | at akka.stream.impl.SubReceive.apply(Transfer.scala:18)
  | at akka.stream.impl.SubReceive.apply(Transfer.scala:14)
  | at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
  | at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
  | at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:14)
  | at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
  | at akka.actor.Actor.aroundReceive(Actor.scala:517)
  | at akka.actor.Actor.aroundReceive$(Actor.scala:515)
  | at akka.stream.impl.io.TLSActor.aroundReceive(TLSActor.scala:50)
  | at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
  | at akka.actor.ActorCell.invoke(ActorCell.scala:557)
  | at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
  | at akka.dispatch.Mailbox.run(Mailbox.scala:225)
  | at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
  | at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  | at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  | at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  | at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by marcospereira** [comment]
Hi @shaneamondos,

Could you better describe how to reproduce this error? What steps are you doing to reach this problem?

Best.

**Comment by devamondos** [comment]
My bad, I have figured out the issue and it was caused from something unrelated to this. I will close this now.
